import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

class Multi_Binary_Classifier(nn.Module):
    def __init__(self, input_size=2048, num_classes=3):
        super(Multi_Binary_Classifier, self).__init__()
        
        self.fc1 = nn.Linear(input_size, num_classes)  # multiple classifier output
        self.fc2 = nn.Linear(num_classes, 1)  # binary classifier output

    def forward(self, x):

        multi_out = self.fc1(x)
        bin_out = self.fc2(multi_out)
        
        return multi_out, bin_out
        


class Classifier(nn.Module):
    def __init__(self, input_size=2048, num_classes=3):
        super(Classifier, self).__init__()
        
        self.fc1 = nn.Linear(input_size, input_size//4) 
        self.fc2 = nn.Linear(input_size//4, num_classes) 

    def forward(self, x):
        x = self.fc1(x)
        out = self.fc2(x)
        
        return out


class CommonClassifier(nn.Module):
    def __init__(self, feature_size=2048, num_classes=1):
        super(CommonClassifier, self).__init__()
        # input shape (B, 1024, 11, 3) 
        self.conv1 = self.conv3 = nn.Conv2d(1024, feature_size, kernel_size=3, bias=False, stride=2, padding=1)
        self.bn1 = nn.BatchNorm2d(feature_size)
        self.conv2 = self.conv3 = nn.Conv2d(feature_size, feature_size, kernel_size=1, bias=False)
        self.bn2 = nn.BatchNorm2d(feature_size)
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))    
        self.fc1 = nn.Linear(feature_size, feature_size//4) 
        self.fc2 = nn.Linear(feature_size//4, num_classes)
        self.relu = nn.ReLU(inplace=True)
        
    def forward(self, x): 

        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)

        x = self.conv2(x)
        x = self.bn2(x)
        x = self.relu(x)

        x = self.avgpool(x) #shape (B, 2048, 1, 1)
        x = x.view(x.size(0), -1)  #shape (B, 2048, 1)
        x = self.fc1(x)
        out = self.fc2(x)
        
        return out         
        
        
class FuseClassifier(nn.Module):
    def __init__(self, num_classes=1, in_f=['layer1', 'layer2', 'layer3', 'feature']):
        super(FuseClassifier, self).__init__()
        self.num_block = len(in_f)
        self.blocks = []
        if 'layer1' in in_f:
            # for feature map of layer1 #input shape (B, 256, 44, 12)
            self.conv1 = nn.Conv2d(256, 1024, kernel_size=7, stride=2, padding=3,
                                   bias=False)
            self.avgpool1 = nn.AdaptiveAvgPool2d((1, 1)) #shape (B, 1024, 1, 1)
            self.blocks.append([self.conv1, self.avgpool1])
            
        if 'layer2' in in_f:
            # for feature map of layer2 #input shape (B, 512, 22, 6)
            self.conv2 = nn.Conv2d(512, 1024, kernel_size=7, stride=2, padding=3,
                                   bias=False)
            self.avgpool2 = nn.AdaptiveAvgPool2d((1, 1))  #shape (B, 1024, 1, 1)                        
            self.blocks.append([self.conv2, self.avgpool2])
            
        if 'layer3' in in_f:
            # for feature map of layer3 #input shape (B, 1024, 11, 3)
            self.conv3 = nn.Conv2d(1024, 1024, kernel_size=1, bias=False)
            self.avgpool3 = nn.AdaptiveAvgPool2d((1, 1))  #shape (B, 1024, 1, 1)
            self.blocks.append([self.conv3, self.avgpool3])
            
        if 'feature' in in_f:
            # for feature map of feature #input shape (B, 2048)
            self.fcf = nn.Linear(2048, 1024)
            self.blocks.append([self.fcf])
            
        self.fc1 = nn.Linear(1024*self.num_block, self.num_block*256)
        self.fc2 = nn.Linear(self.num_block*256, 128)
        self.fc3 = nn.Linear(128, 1)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=0.3)
        
        
    def forward(self, in_features):
        n = len(in_features) # {layer1, layer2, layer3, feature}
        # suppose the data generated by the dataloader has the size of (batch, 25)
        fuse_features = torch.empty((in_features[0].size(0), 0), dtype=torch.float32).cuda()

        assert self.num_block == n, f"please check the number and sequence of fuse features are correct {self.num_block}, {n}."
        for i_block, block in enumerate(self.blocks):
            x = in_features[i_block]
            for j_layer, layer in enumerate(block):
                x = layer(x)
            # print(x.size())    
            x = x.view(x.size(0), -1)    
            fuse_features = torch.cat((fuse_features, x), 1)
            # print(fuse_features.size())
            
        out = self.fc1(fuse_features)
        out = self.relu(out)
        
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc3(out)
        
        return out
            

        
                
                
        
        
        
        
